### ISSUE TITLE
[Issue]: Missing import sdk/server/fetch.ts

### ISSUE THREAD

**Issue by Swahjak** [wundergraph/wundergraph#1310]
### Description

It seems that https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/server/plugins/fetch.ts is missing an import for `Response` resulting in (when --debug is enabled):

```
14:40:21.663 WARN  @wundergraph/server upstream fetch failed type="OpenAPI" error={"type":"ReferenceError","message":"Response is not defined","stack":"ReferenceError: Response is not defined\n    at fn (/var/www/experiments/wundergraph/node_modules/.pnpm/@wundergraph+sdk@0.179.0/node_modules/@wundergraph/sdk/src/server/plugins/fetch.ts:32:4)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async field.resolve (/var/www/experiments/wundergraph/node_modules/.pnpm/@omnigraph+json-schema@0.95.7_@graphql-mesh+cross-helpers@0.4.1_@graphql-mesh+types@0.95.6_@g_4fasnebgtlgnpf62ldxqm6bxx4/node_modules/@omnigraph/json-schema/cjs/addRootFieldResolver.js:206:26)\n    at async Promise.all (index 0)\n    at async /var/www/experiments/wundergraph/node_modules/.pnpm/graphql-helix@1.13.0_graphql@16.8.1/node_modules/graphql-helix/dist/process-request.js:182:36\n    at async processRequest (/var/www/experiments/wundergraph/node_modules/.pnpm/graphql-helix@1.13.0_graphql@16.8.1/node_modules/graphql-helix/dist/process-request.js:59:20)\n    at Object.handler (/var/www/experiments/wundergraph/node_modules/.pnpm/@wundergraph+sdk@0.179.0/node_modules/@wundergraph/sdk/src/server/plugins/omnigraphOAS.ts:36:19)"}
```

### Reproduction

Enable `--debug` (and possibly `--log`).

**Comment by Pagebakers** [comment]
@swahjak what node version are you on?

**Comment by Swahjak** [comment]
Node 16.18.1, PNPM 8.5.1.

```json
  "dependencies": {
    "@wundergraph/nextjs": "^0.14.5",
    "@wundergraph/sdk": "^0.179.0",
    "graphql": "^16.3.0",
    "next": "^13.1.1",
    "react": "^18.0.0",
    "react-dom": "^18.0.0",
    "swr": "^2.2.0"
  },
  "devDependencies": {
    "@jest/globals": "^29.3.1",
    "@playwright/test": "^1.28.1",
    "@types/node": "^17.0.15",
    "@types/node-fetch": "^2.6.2",
    "@types/react": "^18.0.6",
    "jest": "^29.6.1",
    "node-fetch": "^2.6.7",
    "npm-run-all": "^4.1.5",
    "open-cli": "^7.0.1",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.8.0",
    "typescript": "^4.8.2",
    "wait-on": "^6.0.1"
  }
```

**Comment by Pagebakers** [comment]
Thanks looks like that's indeed the case. Response should be imported with node 16.

Will open an internal issue to fix this.

**Comment by Pagebakers** [comment]
Opened a PR to fix this, however Node 16 is EOL and we recommend updating to Node 18 asap.
