### ISSUE TITLE
[Issue]: Crash in Subscriptions after publishing an event to NATS.

### ISSUE THREAD

**Issue by AndriiTsok** [wundergraph/wundergraph#1366]
### Description

We have a federated apollo subgraphs that we connected into a federated graph with Wundergraph Cosmo router. All the queries and mutations perform fine. We defined in our Node subgraph a subscription customerUpdated(id: ID!): Customer! @eventsSubscribe(topic: "customerUpdated.{{ args.id }}")

We can run the router and it work fine, we can even subscribe to the subscription and the playground awaits for the result. 

By pushing a message to NATS: 
```bash 
nats pub customerUpdated.cus_gngkYWNiMzNlZGUtNWJjZC00MjNhLWI2Y2EtNGZmYmUxZDRiNzI3ZmxlZ2FjeQ "{ \"id\":\"cus_gngkYWNiMzNlZGUtNWJjZC00MjNhLWI2Y2EtNGZmYmUxZDRiNzI3ZmxlZ2FjeQ\", \"__typename\":\"Customer\" }"
```

We experiencing Router crash:

```typescript
22:41:51 PM INFO /graphql {"component": "@wundergraph/router", "service_version": "0.57.0", "status": 0, "method": "GET", "path": "/graphql", "query": "", "ip": "127.0.0.1:39352", "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", "latency": 0.00312375, "config_version": "", "request_id": "bfcab1c54241/gododIVTNx-000001", "federated_graph_name": ""}
Worker exits from a panic: runtime error: invalid memory address or nil pointer dereference
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
golang.org/x/sync/singleflight.newPanicError({0xe021c0?, 0x1e1ae20})
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:44 +0x28
golang.org/x/sync/singleflight.(*Group).doCall.func2.1()
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:193 +0x40
panic({0xe021c0?, 0x1e1ae20?})
        runtime/panic.go:914 +0x218
github.com/wundergraph/graphql-go-tools/v2/pkg/ast.(*Document).NodeByName(...)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/ast/ast.go:232
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan.(*fieldSelectionRewriter).processInterfaceSelection(0x40003852e8, 0x40005da325?, 0xb?)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/engine/plan/abstract_selection_rewriter.go:244 +0x64
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan.(*fieldSelectionRewriter).RewriteFieldSelection(0x40003852e8, 0x3, {0x40002c4820?, 0x2?})
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/engine/plan/abstract_selection_rewriter.go:88 +0xe4
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan.(*configurationVisitor).rewriteSelectionSetOfFieldWithInterfaceType(0x400055adc0, 0x0?, 0x0)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/engine/plan/configuration_visitor.go:1179 +0x14c
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan.(*configurationVisitor).EnterField(0x400055adc0, 0x3)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/engine/plan/configuration_visitor.go:370 +0x3f0
github.com/wundergraph/graphql-go-tools/v2/pkg/astvisitor.(*Walker).walkField(0x40004e8300, 0x3, {0x40003411a0?, 0xf55d40?, 0x400055adc0?})
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/astvisitor/visitor.go:1864 +0x210
github.com/wundergraph/graphql-go-tools/v2/pkg/astvisitor.(*Walker).walkSelectionSet(0x40004e8300, 0x2, {0x40003411a0?, 0xf55d40?, 0x400055adc0?})
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/astvisitor/visitor.go:1806 +0x470
github.com/wundergraph/graphql-go-tools/v2/pkg/astvisitor.(*Walker).walkOperationDefinition(0x40004e8300, 0x0, {0x40003411a0?, 0xf55d40?, 0x400055adc0?})
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/astvisitor/visitor.go:1661 +0x2f4
github.com/wundergraph/graphql-go-tools/v2/pkg/astvisitor.(*Walker).walk(0x40004e8300)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/astvisitor/visitor.go:1540 +0x69c
github.com/wundergraph/graphql-go-tools/v2/pkg/astvisitor.(*Walker).Walk(0x4000385a48?, 0x40005ca000?, 0xb?, 0xd90840?)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/astvisitor/visitor.go:1351 +0xd8
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan.(*Planner).findPlanningPaths(0x4000452aa0, 0x4000565400, 0x4000198a00, 0x40004ecd80)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/engine/plan/planner.go:190 +0x1f4
github.com/wundergraph/graphql-go-tools/v2/pkg/engine/plan.(*Planner).Plan(0x4000452aa0, 0x40005ca000?, 0xb?, {0x40003459c0?, 0x40007db000?}, 0x40004ecd80)
        github.com/wundergraph/graphql-go-tools/v2@v2.0.0-rc.2.0.20240122172138-bbfa351e99f1/pkg/engine/plan/planner.go:95 +0x138
github.com/wundergraph/cosmo/router/core.(*OperationPlanner).preparePlan(0x4000446260, {0x40003459c0, 0xe, 0x1ebd4?}, {0x40005da1e0, 0x5f})
        github.com/wundergraph/cosmo/router/core/operation_planner.go:54 +0x44c
github.com/wundergraph/cosmo/router/core.(*OperationPlanner).Plan.func1()
        github.com/wundergraph/cosmo/router/core/operation_planner.go:108 +0x90
golang.org/x/sync/singleflight.(*Group).doCall.func2(0x4000387886, 0x40002c5310, 0x1?)
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:198 +0x60
golang.org/x/sync/singleflight.(*Group).doCall(0xdf8920?, 0x40004ecd50?, {0x40002b62a0?, 0x13?}, 0x8?)
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:200 +0x84
golang.org/x/sync/singleflight.(*Group).Do(0x4000446260, {0x40002b62a0, 0x13}, 0x40004eccf0?)
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:113 +0x1bc
github.com/wundergraph/cosmo/router/core.(*OperationPlanner).Plan(0x4000446260, 0x40004ee780, 0x400031b470, {0xfaa068, 0x2}, {0x0, 0x1, 0x1, 0x1, 0x1, ...})
        github.com/wundergraph/cosmo/router/core/operation_planner.go:106 +0x3a8
github.com/wundergraph/cosmo/router/core.(*WebSocketConnectionHandler).parseAndPlan(0x40005160e0, {0x4000104800?, 0x1418be0?, 0x400027f9e0?})
        github.com/wundergraph/cosmo/router/core/websocket.go:567 +0xd0
github.com/wundergraph/cosmo/router/core.(*WebSocketConnectionHandler).executeSubscription(0x40005160e0, 0x400031b650, {0x4000350c60?, 0xd90900?, 0xe8?})
        github.com/wundergraph/cosmo/router/core/websocket.go:579 +0x8c
github.com/wundergraph/cosmo/router/core.(*WebSocketConnectionHandler).handleSubscribe(0x40005160e0, 0x400031b650)
        github.com/wundergraph/cosmo/router/core/websocket.go:641 +0xf0
github.com/wundergraph/cosmo/router/core.(*WebsocketHandler).HandleMessage.func1()
        github.com/wundergraph/cosmo/router/core/websocket.go:673 +0x30
github.com/alitto/pond.(*WorkerPool).executeTask(0x40002ece40, 0x0?, 0x0?)
        github.com/alitto/pond@v1.8.3/pond.go:454 +0xc8
github.com/alitto/pond.worker({0x1413dd8, 0x4000266640}, 0x0?, 0x0?, 0x400009c180, 0x400027f880)
        github.com/alitto/pond@v1.8.3/worker.go:32 +0x9c
created by github.com/alitto/pond.(*WorkerPool).maybeStartWorker in goroutine 21
        github.com/alitto/pond@v1.8.3/pond.go:423 +0x154
Stack trace: goroutine 52 [running]:
runtime/debug.Stack()
        runtime/debug/stack.go:24 +0x64
github.com/alitto/pond.defaultPanicHandler({0xe14f60?, 0x40004ed080})
        github.com/alitto/pond@v1.8.3/pond.go:26 +0x28
github.com/alitto/pond.(*WorkerPool).executeTask.func1()
        github.com/alitto/pond@v1.8.3/pond.go:437 +0x78
panic({0xe14f60?, 0x40004ed080?})
        runtime/panic.go:914 +0x218
golang.org/x/sync/singleflight.(*Group).doCall.func1()
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:170 +0x2d0
golang.org/x/sync/singleflight.(*Group).doCall(0xdf8920?, 0x40004ecd50?, {0x40002b62a0?, 0x13?}, 0x8?)
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:205 +0xa4
golang.org/x/sync/singleflight.(*Group).Do(0x4000446260, {0x40002b62a0, 0x13}, 0x40004eccf0?)
        golang.org/x/sync@v0.4.0/singleflight/singleflight.go:113 +0x1bc
github.com/wundergraph/cosmo/router/core.(*OperationPlanner).Plan(0x4000446260, 0x40004ee780, 0x400031b470, {0xfaa068, 0x2}, {0x0, 0x1, 0x1, 0x1, 0x1, ...})
        github.com/wundergraph/cosmo/router/core/operation_planner.go:106 +0x3a8
github.com/wundergraph/cosmo/router/core.(*WebSocketConnectionHandler).parseAndPlan(0x40005160e0, {0x4000104800?, 0x1418be0?, 0x400027f9e0?})
        github.com/wundergraph/cosmo/router/core/websocket.go:567 +0xd0
github.com/wundergraph/cosmo/router/core.(*WebSocketConnectionHandler).executeSubscription(0x40005160e0, 0x400031b650, {0x4000350c60?, 0xd90900?, 0xe8?})
        github.com/wundergraph/cosmo/router/core/websocket.go:579 +0x8c
github.com/wundergraph/cosmo/router/core.(*WebSocketConnectionHandler).handleSubscribe(0x40005160e0, 0x400031b650)
        github.com/wundergraph/cosmo/router/core/websocket.go:641 +0xf0
github.com/wundergraph/cosmo/router/core.(*WebsocketHandler).HandleMessage.func1()
        github.com/wundergraph/cosmo/router/core/websocket.go:673 +0x30
github.com/alitto/pond.(*WorkerPool).executeTask(0x40002ece40, 0x0?, 0x0?)
        github.com/alitto/pond@v1.8.3/pond.go:454 +0xc8
github.com/alitto/pond.worker({0x1413dd8, 0x4000266640}, 0x0?, 0x0?, 0x400009c180, 0x400027f880)
        github.com/alitto/pond@v1.8.3/worker.go:32 +0x9c
created by github.com/alitto/pond.(*WorkerPool).maybeStartWorker in goroutine 21
        github.com/alitto/pond@v1.8.3/pond.go:423 +0x154
``` 

### Reproduction

```
directive @eventsSubscribe(topic: String!) on FIELD_DEFINITION

scalar DateTime

interface Node @key(fields: "id") {
  id: ID!
}

type Customer implements Node @key(fields: "id") {
  id: ID!
}

type Query {
  node(id: ID!): Node
}

type Subscription {
  customerUpdated(id: ID!): Customer! @eventsSubscribe(topic: "customerUpdated.{{ args.id }}")
}

extend schema
  @link(
    url: "https://specs.apollo.dev/federation/v2.3"
    import: ["@key", "@shareable", "@external"]
  )

``` 

Also, there is a Customer subgraph that resolves some other properties.

**Comment by jensneuse** [comment]
Can you publish a reproducible of sort? A test, a demo, anything to verify this?

**Comment by AndriiTsok** [comment]
@jensneuse yes, I am preparing a small repro.

**Comment by AndriiTsok** [comment]
Hello @jensneuse 

I have prepared a repo with a small repro example: https://github.com/AndriiTsok/wundergraph-subscriptions-crash-repro 
Feel free to use Codespace to open it. The dev container includes everything to startup the sample. Once it all live and codespace is ready you can run multiple terminals to:
1. Start nats:  `nats-server` command.
2. The container include nats cli set up.

One the Codespace live you can start the sample by running:
`nx run-many -t serve --all --parallel=30 --skip-nx-cache` to start three nodejs (apollo federated subgraphs) and the wgc router.

Once all is running the subgraphs you can see PORTS tab, the router will be at 3002 port.
<img width="1088" alt="Screenshot 2024-01-27 at 1 06 01 AM" src="https://github.com/wundergraph/wundergraph/assets/733224/dc86d411-efeb-4b65-b722-99b7f1565838">


#Actual behavior:

I can subscribe to customerUpdated subscription, but it always show me an error when I supply a nats event: `nats pub customerUpdated.Customer:123 '{ "id":"Customer:123", "__typename": "Customer" }'`

<img width="1403" alt="Screenshot 2024-01-27 at 12 51 29 AM" src="https://github.com/wundergraph/wundergraph/assets/733224/b12462c6-19d9-4bae-99b3-f4dcfd88fa16">

Also, I noticed that the added subscription breaks the `node` query as well:

<img width="1042" alt="Screenshot 2024-01-27 at 12 54 31 AM" src="https://github.com/wundergraph/wundergraph/assets/733224/8bddb800-5cb8-4923-b42f-66b2483a127c">

With a log:

```bash
05:57:33 AM ERROR internal error {"component": "@wundergraph/router", "service_version": "0.59.0", "reqId": "f5789941e01903945e04431ea6a45100", "error": "1 error occurred:\n\t* bad datasource configuration - could not plan the operation\n\n"}
github.com/wundergraph/cosmo/router/core.logInternalErrorsFromReport
        github.com/wundergraph/cosmo/router/core/graphql_handler.go:200
github.com/wundergraph/cosmo/router/core.(*PreHandler).writeOperationError
        github.com/wundergraph/cosmo/router/core/graphql_prehandler.go:315
github.com/wundergraph/cosmo/router/core.(*PreHandler).Handler-fm.(*PreHandler).Handler.func1
        github.com/wundergraph/cosmo/router/core/graphql_prehandler.go:220
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/wundergraph/cosmo/router/core.(*WebsocketHandler).ServeHTTP
        github.com/wundergraph/cosmo/router/core/websocket.go:163
github.com/go-chi/chi.(*Mux).ServeHTTP
        github.com/go-chi/chi@v1.5.4/mux.go:70
github.com/go-chi/chi.(*Mux).Mount.func1
        github.com/go-chi/chi@v1.5.4/mux.go:311
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/go-chi/chi.(*Mux).routeHTTP
        github.com/go-chi/chi@v1.5.4/mux.go:436
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/wundergraph/cosmo/router/pkg/cors.(*cors).ServeHTTP
        github.com/wundergraph/cosmo/router/pkg/cors/config.go:74
github.com/wundergraph/cosmo/router/internal/requestlogger.(*handler).ServeHTTP
        github.com/wundergraph/cosmo/router/internal/requestlogger/requestlogger.go:76
github.com/wundergraph/cosmo/router/pkg/trace.(*Middleware).Handler.func1
        github.com/wundergraph/cosmo/router/pkg/trace/middleware.go:41
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.(*middleware).serveHTTP
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:229
go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp.NewMiddleware.func1.1
        go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp@v0.46.1/handler.go:81
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/go-chi/chi/middleware.RealIP.func1
        github.com/go-chi/chi@v1.5.4/middleware/realip.go:34
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/go-chi/chi/middleware.RequestID.func1
        github.com/go-chi/chi@v1.5.4/middleware/request_id.go:76
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/wundergraph/cosmo/router/internal/recoveryhandler.(*handler).ServeHTTP
        github.com/wundergraph/cosmo/router/internal/recoveryhandler/recovery.go:103
github.com/wundergraph/cosmo/router/core.(*Router).newServer.func2.1
        github.com/wundergraph/cosmo/router/core/router.go:742
net/http.HandlerFunc.ServeHTTP
        net/http/server.go:2136
github.com/go-chi/chi.(*Mux).ServeHTTP
        github.com/go-chi/chi@v1.5.4/mux.go:87
net/http.serverHandler.ServeHTTP
        net/http/server.go:2938
net/http.(*conn).serve
        net/http/server.go:2009
```

Also, I just tried to update all dependencies, global and local to the latest version. You can see version in the package json.


About an hour ago, I noted about this issue: https://github.com/wundergraph/cosmo/issues/442 
I tried and it still does not work. 

What I observing is that if I remove the `@eventsSubscribe` or the whole subscription from schema definition. The node query starts to work fine. 

I couldn't dig deeper, but I am willing to provide more information if you need.

Hope we can quickly resolve this. Our team is dreaming now to migrate from Apollo to Wundergraph! You guys have an amazing product!

**Comment by Aenimus** [comment]
Hi @AndriiTsok,

I've been investigating this. I see some issues with what you've provided, but I wanted to see the error itself first hand.

I've tried to run your example through Codespaces, but all the services are fighting over port 3000. I tried to tweak things to get it to work, but I am unfamiliar with both codespaces and nx, and the problem persisted.

For example, I tried to add a port to the serve options of the project-graph.json, but my changes wouldn't stick (again, I am not familiar with Codespaces). I also tried to serve with the `--port` param, but this only seemed to affect the debugger.

Please try the command you suggested yourself and let me know whether you have more luck.

**Comment by Aenimus** [comment]
Another note, I had to move the router because it was pointing to the incorrect directory. Are you sure this worked on Codespaces as presented?

**Comment by Aenimus** [comment]
@AndriiTsok Unfortunately, I keep getting a segmentation fault whenever I try to do anything with nats, so I was unable to reproduce e2e.

However, I believe I understand the cause of your issue.

You are contributing a new field (i.e., one that is not defined in any other subgraph) in subgraph-b through "name". The subgraph the defines the event subscription must only contain the fields (and potentially objects) required by the primary key. The subgraph should also not define any resolvers or anything like that—think of it as an abstraction layer.

Here is some relevant documentation: https://cosmo-docs.wundergraph.com/router/event-driven-federated-subscriptions-edfs#request-reply

To fix your issue, make sure name is defined (and resolved) in another graph. Remove it (and the resolvers—but these will not be used) from subgraph-b.

We'll try to improve the documentation and also add explicit errors in composition to make it clear that you cannot do this.

**Comment by jensneuse** [comment]
Handled in Cosmo repo.
