### ISSUE TITLE
Custom request headers not working when using `wunderctl generate`

### ISSUE THREAD

**Issue by blegrosvoalte** [wundergraph/wundergraph#150]
### Bug description

I currently have a GraphQL subgraph written in Apollo, running on NodeJS, exposing a federated schema (ie - the `_service` field).  When trying to use Wundergraph as an Apollo Federated Gateway in a Docker image, in the build layer, I'm getting an HTTP response with a status code of 400 when `wunderctl generate` is called.  The 400 status code from the subgraph occurs when a set of custom headers and the `Authorization` header are not passed.  

Is there a way to specify a set of headers to the `wunderctl generate` call so it can get the result of the `query { _service { sdl } }` w/o disabling these required headers on the subgraph?  

Below is my Dockerfile:

```
# Image layer for building the application
FROM node:16-buster-slim as build

# global npm dependencies: recommended to place those dependencies in the non-root user directory
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
# optionally if you want to run npm global bin without specifying path
ENV PATH=$PATH:/home/node/.npm-global/bin

ARG SUBGRAPH_URLS

RUN apt update
RUN apt install -y curl

WORKDIR /usr/src/app

# rebuild image when package.json or lock has changed
COPY package*.json ./

# install dependencies
RUN npm ci --only=production

# install wunderctl in correct version
RUN curl -s -L https://github.com/wundergraph/wundergraph/releases/download/v0.100.0/wunderctl_0.100.0_Linux_x86_64.tar.gz | tar xzvf - && \
    chmod +x wunderctl && mv wunderctl /usr/local/bin
RUN wunderctl version

# add project artifacts to docker image
ADD . .

# generate your wundergraph application
RUN cd .wundergraph && wunderctl generate

# Image layer for production
FROM node:16-buster-slim as runner
WORKDIR /usr/src/app

# copy entire project and dependencies
COPY --from=build --chown=node:node /usr/src/app/node_modules ./node_modules
COPY --from=build --chown=node:node /usr/src/app/.wundergraph ./.wundergraph
# copy wunderctl to start the server
COPY --from=build --chown=node:node /usr/local/bin/wunderctl /usr/local/bin/wunderctl

# run as non-root user
USER node

WORKDIR .wundergraph

CMD wunderctl start --listen-addr 0.0.0.0:9991 --debug

EXPOSE 9991
```

and the wundergraph.config.ts file:

```
import {
    Application,
    configureWunderGraphApplication,
    cors,
    introspect,
} from '@wundergraph/sdk';
import server from './wundergraph.server';
import operations from './wundergraph.operations';

function buildHeaders(builder) {
    return builder
        .addClientRequestHeader('Authorization', 'Authorization')
        .addClientRequestHeader('X-Custom-1', 'X-Custom-1')
        .addClientRequestHeader('X-Custom-2', 'X-Custom-2')
        .addClientRequestHeader('X-Custom-3', 'X-Custom-3');
}

const subgraphUrls = process.env.SUBGRAPH_URLS;
if(!subgraphUrls) {
    throw new Error('No subgraph URLs provided!');
}

const upstreams = subgraphUrls.split(',').map(url => ({
    url,
    headers: buildHeaders
}));

const federatedApi = introspect.federation({
    upstreams
});

const myApplication = new Application({
    name: 'federated-gateway',
    apis: [federatedApi]
});

// configureWunderGraph emits the configuration
configureWunderGraphApplication({
    application: myApplication,
    server,
    operations,
    cors: {
        ...cors.allowAll,
        allowedOrigins: ['https://studio.apollographql.com']
    },
    security: {
        enableGraphQLEndpoint: true,
    },
});
```

A snippet of the error I receive when building the Docker image is below (the entire error seems to be a debug stack trace that's hundreds of lines long):

```
[+] Building 30.4s (14/19)                                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                                      0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 34B                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/node:16-buster-slim                                                                                                                                    0.0s
 => CACHED [build  1/10] FROM docker.io/library/node:16-buster-slim                                                                                                                                       0.0s
 => [internal] load build context                                                                                                                                                                         0.0s
 => => transferring context: 151.03kB                                                                                                                                                                     0.0s
 => [build  2/10] RUN apt update                                                                                                                                                                          4.3s
 => [build  3/10] RUN apt install -y curl                                                                                                                                                                 6.4s
 => [build  4/10] WORKDIR /usr/src/app                                                                                                                                                                    0.0s 
 => [build  5/10] COPY package*.json ./                                                                                                                                                                   0.0s 
 => [build  6/10] RUN npm ci --only=production                                                                                                                                                           15.3s
 => [build  7/10] RUN curl -s -L https://github.com/wundergraph/wundergraph/releases/download/v0.100.0/wunderctl_0.100.0_Linux_x86_64.tar.gz | tar xzvf - &&     chmod +x wunderctl && mv wunderctl /usr  1.7s
 => [build  8/10] RUN wunderctl version                                                                                                                                                                   0.4s
 => [build  9/10] ADD . .                                                                                                                                                                                 0.0s
 => ERROR [build 10/10] RUN cd .wundergraph && wunderctl generate                                                                                                                                         2.2s
------
 > [build 10/10] RUN cd .wundergraph && wunderctl generate:
#15 2.101 uncaught exception, origin: unhandledRejection, error: Error: Request failed with status code 400
#15 2.115 /usr/src/app/node_modules/axios/lib/core/createError.js:16
#15 2.115   var error = new Error(message);
#15 2.115               ^
#15 2.115 
#15 2.115 Error: Request failed with status code 400
#15 2.115     at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)
#15 2.115     at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)
#15 2.115     at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:322:11)
#15 2.115     at IncomingMessage.emit (node:events:525:35)
#15 2.115     at endReadableNT (node:internal/streams/readable:1358:12)
#15 2.115     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
#15 2.115   config: {
#15 2.115     transitional: {
#15 2.115       silentJSONParsing: true,
#15 2.115       forcedJSONParsing: true,
#15 2.115       clarifyTimeoutError: false
#15 2.115     },
#15 2.115     adapter: [Function: httpAdapter],
#15 2.115     transformRequest: [ [Function: transformRequest] ],
#15 2.115     transformResponse: [ [Function: transformResponse] ],
#15 2.115     timeout: 0,
#15 2.115     xsrfCookieName: 'XSRF-TOKEN',
#15 2.115     xsrfHeaderName: 'X-XSRF-TOKEN',
#15 2.115     maxContentLength: -1,
#15 2.115     maxBodyLength: -1,
#15 2.115     validateStatus: [Function: validateStatus],
#15 2.115     headers: {
#15 2.115       Accept: 'application/json',
#15 2.115       'Content-Type': 'application/json',
#15 2.115       'User-Agent': 'axios/0.26.1',
#15 2.115       'Content-Length': 27
#15 2.115     },
#15 2.115     method: 'post',
#15 2.115     url: 'https://<redacted>/graphql',
#15 2.115     data: '{"query":"{_service{sdl}}"}'
#15 2.115   },
```

### How to reproduce

1. Create a Apollo Federation compliant subgraph which returns an HTTP status code of 400 when a custom header (eg - X-Custom-1) isn't provided on the HTTP request. 
2. Create a `Dockerfile` using the provided one as a template
3. Build the Docker image
4. `wunderctl generate` will fail due with an error saying the HTTP request received a 400 status code

### WunderGraph information

See description.

### Environment & setup

- OS: OSX
- Go version: version bundled with wunderctl
- Database: na
- Node.js version: 16.x

### WunderCtl Version

```
$ wunderctl version
Version: 0.100.0
Commit: b60912fb6ab2830aa19c69f0b593f13f2dd75476
Date: 2022-08-29T14:51:18Z
BuiltBy: ci

```

**Comment by jensneuse** [comment]
This is now possible through:
https://docs.wundergraph.com/docs/wundergraph-config-ts-reference/configure-introspection#provide-headers-with-introspection-configuration
