### ISSUE TITLE
SWR not installed in package.json

### ISSUE THREAD

**Issue by SimonKlausLudwig** [wundergraph/wundergraph#391]
### Bug description

Error

error - ./node_modules/@wundergraph/swr/dist/hooks.js:31:0
Module not found: Package path ./mutation is not exported from package /Users/simonludwig/Downloads/projects/world/node_modules/swr (see exports field in /Users/simonludwig/Downloads/projects/world/node_modules/swr/package.json)

Import trace for requested module:
./node_modules/@wundergraph/swr/dist/index.js
./node_modules/@wundergraph/nextjs/dist/index.js
./components/generated/nextjs.ts
./pages/index.tsx

https://nextjs.org/docs/messages/module-not-found
error - Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './mutation' is not defined by "exports" in /Users/simonludwig/Downloads/projects/world/node_modules/swr/package.json
    at new NodeError (node:internal/errors:387:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:439:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:718:3)
    at resolveExports (node:internal/modules/cjs/loader:493:36)
    at Module._findPath (node:internal/modules/cjs/loader:533:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:942:27)
    at mod._resolveFilename (/Users/simonludwig/Downloads/projects/world/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/simonludwig/Downloads/projects/world/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at mod._resolveFilename (/Users/simonludwig/Downloads/projects/world/node_modules/next/dist/build/webpack/require-hook.js:27:32)
    at Module._load (node:internal/modules/cjs/loader:804:27) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED',
  page: '/'
}

I had to install swr@2.0.0-rc.3 to get rid of the error 

### How to reproduce

Just use npx and create the project

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by Pagebakers** [comment]
Thanks for reporting @SimonKlausLudwig swr@2.0.0-rc is a required peer dependency in the latest release, but it looks like it might be missing in the example. We're on it.

**Comment by Pagebakers** [comment]
All example apps should now be updated, thanks again for reporting!
