### ISSUE TITLE
OAS: error on parameter names and enum names with '.'

### ISSUE THREAD

**Issue by emrosenf** [wundergraph/wundergraph#436]
### Bug description

A parameter name with a '.', e.g. `sort.order`, or an enum name like `sort_order.asc` will throw an error:

```
 FAIL  ./index.test.ts
  ✕ arbitrary type (68 ms)

  ● arbitrary type

    GraphQLError: Syntax Error: Unexpected character: ".".

      25 |      let customScalarTypeFields: SingleTypeField[] = [];
      26 |
    > 27 |      const ast = parse(schemaSDL);
         |                       ^
      28 |      const cleanAst = visit(ast, {
      29 |              ObjectTypeDefinition: {
      30 |                      enter: (node) => {

      at syntaxError (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/error/syntaxError.js:15:10)
      at readNextToken (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/lexer.js:420:40)
      at Lexer.lookahead (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/lexer.js:84:29)
      at Lexer.advance (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/lexer.js:67:38)
      at Parser.advanceLexer (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1536:31)
      at Parser.expectToken (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1393:12)
      at Parser.parseName (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:108:24)
      at Parser.parseInputValueDef (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:869:23)
      at Parser.optionalMany (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1492:28)
      at Parser.parseArgumentDefs (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:855:17)
      at Parser.parseFieldDefinition (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:837:23)
      at Parser.optionalMany (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1492:28)
      at Parser.parseFieldsDefinition (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:822:17)
      at Parser.parseObjectTypeDefinition (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:794:25)
      at Parser.parseDefinition (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:172:23)
      at Parser.many (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:1511:26)
      at Parser.parseDocument (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:122:25)
      at parse (../../../../node_modules/.pnpm/graphql@16.6.0/node_modules/graphql/language/parser.js:32:17)
      at Object.replaceCustomScalars (../transformations/shema.ts:27:19)
      at RESTApiBuilder.build (index.ts:143:75)
      at openApiSpecificationToRESTApiObject (index.ts:69:19)
      at Object.<anonymous> (index.test.ts:106:17)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        4.165 s
Ran all test suites.
```

### How to reproduce

Use this schema, based on `users_meta.json`

```
{
  "openapi": "3.0.0",
  "info": {
    "title": "users",
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:8881"
    }
  ],
  "paths": {
    "/users": {
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/User"
                  }
                }
              }
            }
          }
        },
        "operationId": "get-users"
      }
    },
    "/users/{user_id}": {
      "parameters": [
        {
          "schema": {
            "type": "integer"
          },
          "name": "user_id",
          "in": "path",
          "required": true
        }
      ],
      "get": {
        "summary": "Your GET endpoint",
        "tags": [],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/User"
                }
              }
            }
          }
        },
        "operationId": "get-users-user_id"
      }
    },
    "/some/properties": {
      "get": {
        "parameters": [
          {
            "name": "sortBy",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "sort.order",
            "in": "query",
            "schema": {
              "type": "array",
              "items": {
                "type": "string",
                "enum": [
                  "sort_order.asc",
                  "sort_order.desc"
                ]
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/PropertiesResponse"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "title": "User",
        "type": "object",
        "properties": {
          "id": {
            "type": "integer"
          },
          "name": {
            "type": "string"
          },
          "country_code": {
            "type": "string"
          },
          "status_code": {
            "$ref": "#/components/schemas/StatusCode"
          },
          "contact": {}
        }
      },
      "PropertiesResponse": {
        "type": "object",
        "properties": {
          "properties": {
            "type": "object",
            "additionalProperties": {
              "type": "string"
            },
            "nullable": true
          }
        },
        "additionalProperties": false
      },
      "StatusCode": {
        "enum": [0, 1, 2],
        "type": "integer",
        "format": "int32"
      }
    }
  }
}
```

### Expected behavior

The engine should rename this parameter `sortOrderAsc`, applying the same convention as used on '-' and '_'

### Environment & setup

- OS: 
- Go version: 
- Database: 
- Node.js version: 

### WunderCtl Version

```

```

**Comment by Pagebakers** [comment]
@emrosenf I tested this with our new open api introspector, and this issue been resolved. We will release the new introspection in the next few weeks. Thanks for your patience.

**Comment by emrosenf** [comment]
@Pagebakers did the new introspection get released yet?

**Comment by Pagebakers** [comment]
@emrosenf we had some issue with our initial release, but the new version should work just fine.

You can now use version 2 like this:
`introspection.openApiV2({
	id: 'oas',
	apiNamespace: 'oas',
	source: {
		kind: 'file',
		filePath: './oas.yml',
	},
	baseURL: 'https://api.net',
	headers: (builder) =>
		builder
			// this header is shared between introspection and actual requests
			.addStaticHeader('x-api-key', 'eeeeeee'),
})`

**Comment by corydeppen** [comment]
I still see an issue with parameter names that include a period. I added the [StackPath OpenAPI doc](https://stackpath.dev/openapi/5cf6ebff8cfef2001a725195) to the `v2openapi/testdata` directory and the [test](https://github.com/wundergraph/wundergraph/blob/main/packages/sdk/src/v2openapi/index.test.ts) failed due to a parsing error.

It looks like initial work was done on #437, but it was closed due to being stale.

```graphql
type Query {
  GetAccountUsers(account_id: String!, page_request.first: String, page_request.after: String, page_request.filter: String, page_request.sort_by: String): identityGetAccountUsersResponse
}
```

```bash
Syntax Error: Cannot parse the unexpected character ".". (2:52)
  1 | type Query {
> 2 |   GetAccountUsers(account_id: String!, page_request.first: String, page_request.after: String, page_request.filter: String, page_request.sort_by: String): identityGetAccountUsersResponse
    |                                                    ^
  3 | }
```
