### ISSUE TITLE
OpenAPI introspect problem WG fails introspecting list of objects defined by $ref

### ISSUE THREAD

**Issue by remeq** [wundergraph/wundergraph#656]
### Bug description

When itrospecting our OpenAPI spec we get following error:

```
/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/graphql/validation/validate.js:135
    throw new Error(errors.map((error) => error.message).join('\n\n'));
          ^

Error: Unknown type "UserOperationWrapperReceiver". Did you mean "UserOperationWrapper" or "UserOperationsPageResponse"?


Unknown type "UserOperationWrapperSender". Did you mean "UserOperationWrapper" or "UserOperationsPageResponse"?
    at assertValidSDL (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/graphql/validation/validate.js:135:11)
    at buildASTSchema (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/graphql/utilities/buildASTSchema.js:44:34)
    at RESTApiBuilder.build (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:63:57)
    at openApiSpecificationToRESTApiObject (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/v2openapi/index.js:30:28)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async generator (/home/ibmko/lab/blockfort/crossplane2/eks/crossplane-prod-ready-eks/garbage/wunder2/kubernetes-deployment/testapp/node_modules/@wundergraph/sdk/dist/definition/index.js:315:20)
```

### How to reproduce

After further investigation we have discovered that it happens when OpenAPI spec contains a list which contains objects specified by reference, for example:

```
        operations:
          type: array
          items:
            $ref: '#/components/schemas/UserOperationWrapper'
```

**Comment by fiam** [comment]
@remeq Thanks for letting us know. We're working on a new framework for introspecting OpenAPI data sources which should fix all these problems. It should be ready quite soon. Once we release it we can revisit this issue to check if the problem still persist.

**Comment by remeq** [comment]
@fiam thanks, do you have a rough estimate when the new implementation will be available ?

**Comment by fiam** [comment]
@remeq Probably within the next two weeks. You can track its progress in this PR https://github.com/wundergraph/wundergraph/pull/621

**Comment by javacode123** [comment]
cook

**Comment by Pagebakers** [comment]
@javacode123 Could you share the oas spec with us?

**Comment by javacode123** [comment]
> @javacode123 Could you share the oas spec with us?

this one https://petstore3.swagger.io/api/v3/openapi.json

**Comment by Pagebakers** [comment]
@remeq Sorry for the delay, we released the new oas introspection which should resolve this issue. Please try it out and let us know if this resolves it for you.

You can use the new `introspection.openApiV2()` method to use the new version.

**Comment by jensneuse** [comment]
Fixed, see last comment.
