### ISSUE TITLE
Crash when closing remote graphql subscription before receiving first message

### ISSUE THREAD

**Issue by andcan** [wundergraph/wundergraph#686]
### Bug description

The server is crashing when terminating subscription before receiving any message.

The error message is:
```
{"level":"debug","time":1676981480059,"caller":"commands/root.go:99","msg":"env file successfully loaded","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/wunderctl","file":".env"}
{"level":"debug","time":1676981480061,"caller":"scriptrunner/scriptrunner.go:175","msg":"Start runner","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/wunderctl","runnerName":"hooks-server-runner"}
{"level":"info","time":1676981480061,"caller":"node/node.go:199","msg":"Api config: static","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/wunderctl","component":"@wundergraph/node"}
{"level":"debug","time":1676981480061,"caller":"node/node.go:432","msg":"http.Client.Transport","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","enableDebugMode":true}
{"level":"debug","time":1676981480061,"caller":"apihandler/apihandler.go:674","msg":"configureCache","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","primaryHost":"0.0.0.0:9991","deploymentID":"","cacheKind":"IN_MEMORY_CACHE","cacheSize":128000000}
{"level":"debug","time":1676981480063,"caller":"apihandler/apihandler.go:406","msg":"create sub router","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node"}
{"level":"debug","time":1676981480064,"caller":"apihandler/apihandler.go:188","msg":"configuring API","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","numOfOperations":1}
{"level":"debug","time":1676981480064,"caller":"apihandler/apihandler.go:249","msg":"configuring CORS","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","allowedOrigins":["http://localhost:3000"]}
{"level":"debug","time":1676981480065,"caller":"apihandler/apihandler.go:638","msg":"registered SubscriptionHandler","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","method":"GET","path":"/operations/sse","mock":false,"authRequired":false}
{"level":"debug","time":1676981480065,"caller":"apihandler/internalapihandler.go:85","msg":"configuring API","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","numOfOperations":1}
{"level":"debug","time":1676981480066,"caller":"node/node.go:560","msg":"public node url","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","publicNodeUrl":"http://localhost:9991"}
{"level":"info","time":1676981480066,"caller":"node/node.go:542","msg":"listening on","hostname":"38ee93c55bb8","pid":28747,"component":"@wundergraph/node","addr":"0.0.0.0:9991"}
{"level":"debug","time":1676981480216,"pid":28759,"hostname":"38ee93c55bb8","component":"@wundergraph/server","msg":"Registered (0) query operations"}
{"level":"debug","time":1676981480216,"pid":28759,"hostname":"38ee93c55bb8","component":"@wundergraph/server","msg":"Registered (0) mutation operations"}
{"level":"info","time":1676981480216,"pid":28759,"hostname":"38ee93c55bb8","component":"@wundergraph/server","msg":"Hooks plugin registered"}
{"level":"info","time":1676981480222,"pid":28759,"hostname":"38ee93c55bb8","component":"@wundergraph/server","msg":"Server listening at http://127.0.0.1:9992"}


--- ClientRequest start ---

GET /operations/sse HTTP/1.1
Host: localhost:9991
Accept: */*
User-Agent: curl/7.74.0





--- ClientRequest end ---

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc3c72e]

goroutine 54 [running]:
github.com/wundergraph/graphql-go-tools/pkg/engine/resolve.(*Context).Value(0xc003e227d8?, {0x12ef080?, 0x20cb828?})
        <autogenerated>:1 +0x2e
context.value({0x16bcd30?, 0xc000144c60?}, {0x12ef080?, 0x20cb828?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/context/context.go:590 +0x1f6
context.(*cancelCtx).Value(0xc0001452d8?, {0x12ef080?, 0x20cb828?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/context/context.go:355 +0x65
net/http/httptrace.ContextClientTrace(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/httptrace/trace.go:25
net/http.(*persistConn).readLoop(0xc000145200)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/transport.go:2104 +0x2ed
created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/transport.go:1750 +0x173e
```

### How to reproduce

Reproduction [devcontainer](https://github.com/andcan/repro-graphql-sse).

Terminal 1:
* `cd sse`
* `npm install`
* `npm run start`

Terminal 2:
* `cd world`
* `npm install`
* `./node_modules/.bin/wunderctl generate` (`npm run start` does not work it has strange behavior)
* `./node_modules/.bin/wunderctl start`

Terminal 3:
* `curl -N http://localhost:9991/operations/sse`
* ctrl+c before receiving message
* Terminal 2 shows error

### Expected behavior

I expect the server to not crash.

### WunderGraph information

See reproduction repo.

### Environment & setup

- OS: Devcontainer mcr.microsoft.com/devcontainers/typescript-node:0-18 on 5.15.94-1-MANJARO
- Go version: NA
- Database: NA
- Node.js version: v18.13.0

### WunderCtl Version

```
Version: 0.131.0
Commit: ef6da9fb2798025bd86026cfac4d9881b66a6d00
Date: 2023-02-10T14:11:04Z
BuiltBy: ci
```

**Comment by fiam** [comment]
Hi @andcan. Thanks for your report. This should be fixed in the latest release (0.138). Could you please upgrade, try it and let us know if it's working for you? Thanks!

**Comment by andcan** [comment]
Upgraded to 0.138.0.

It's still crashing:
```
{"level":"info","time":1678371540019,"msg":"Api config: static","hostname":"9074477a0296","pid":832,"component":"@wundergraph/wunderctl","component":"@wundergraph/node"}
{"level":"error","time":1678371540019,"msg":"The secret WG_CSRF_TOKEN_SECRET was unset. A temporary randomised value has been created; please generate a new one. https://docs.wundergraph.com/docs/self-hosted/security","hostname":"9074477a0296","pid":832,"component":"@wundergraph/node"}
{"level":"error","time":1678371540019,"msg":"The secret WG_SECURE_COOKIE_HASH_KEY was unset. A temporary randomised value has been created; please generate a new one. https://docs.wundergraph.com/docs/self-hosted/security","hostname":"9074477a0296","pid":832,"component":"@wundergraph/node"}
{"level":"error","time":1678371540019,"msg":"The secret WG_SECURE_COOKIE_BLOCK_KEY was unset. A temporary randomised value has been created; please generate a new one. https://docs.wundergraph.com/docs/self-hosted/security","hostname":"9074477a0296","pid":832,"component":"@wundergraph/node"}
{"level":"info","time":1678371540023,"msg":"listening on","hostname":"9074477a0296","pid":832,"component":"@wundergraph/node","addr":"0.0.0.0:9991"}
{"level":"info","time":1678371540172,"pid":844,"hostname":"9074477a0296","component":"@wundergraph/server","msg":"Hooks plugin registered"}
{"level":"info","time":1678371540178,"pid":844,"hostname":"9074477a0296","component":"@wundergraph/server","msg":"Server listening at http://127.0.0.1:9992"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xc3d5ce]

goroutine 32 [running]:
github.com/wundergraph/graphql-go-tools/pkg/engine/resolve.(*Context).Value(0xc00009b438?, {0x12f52e0?, 0x20d37a8?})
        <autogenerated>:1 +0x2e
context.value({0x16c3b40?, 0xc000696ea0?}, {0x12f52e0?, 0x20d37a8?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/context/context.go:590 +0x1f6
context.(*cancelCtx).Value(0xc0006973f8?, {0x12f52e0?, 0x20d37a8?})
        /opt/hostedtoolcache/go/1.18.10/x64/src/context/context.go:355 +0x65
net/http/httptrace.ContextClientTrace(...)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/httptrace/trace.go:25
net/http.(*persistConn).readLoop(0xc000697320)
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/transport.go:2104 +0x2ed
created by net/http.(*Transport).dialConn
        /opt/hostedtoolcache/go/1.18.10/x64/src/net/http/transport.go:1750 +0x173e
```

**Comment by fiam** [comment]
Thanks for the confirmation. We're looking into it.

**Comment by fiam** [comment]
@andcan This is now fixed. If you upgrade to the latest SDK, you shouldn't see this anymore. Thanks for reporting it!
